# Generated by Django 3.1 on 2024-05-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nikename_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_nickname',
        ),
    ]
