# Generated by Django 3.1 on 2024-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nikename_url',
            field=models.URLField(default='https://www.facebook.com/profile.php?id=100068020764035'),
        ),
        migrations.DeleteModel(
            name='UserUrl',
        ),
    ]
