# Generated by Django 3.1 on 2024-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdegree'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userdegree',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserDegree',
        ),
    ]
