# Generated by Django 3.1 on 2024-04-28 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Display_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosenum', models.IntegerField()),
                ('puplish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('displays', models.ManyToManyField(related_name='display_data', to='display.Display')),
                ('users', models.ManyToManyField(related_name='display_user', to='accounts.UserProfile')),
            ],
        ),
    ]
