# Generated by Django 3.1 on 2024-04-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_data',
            name='users',
        ),
        migrations.AddField(
            model_name='display_data',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
