# Generated by Django 3.1 on 2024-04-07 08:47

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='display',
            options={},
        ),
        migrations.RemoveField(
            model_name='display',
            name='choosenum',
        ),
        migrations.RemoveField(
            model_name='display',
            name='puplish_date',
        ),
        migrations.RemoveField(
            model_name='display',
            name='user',
        ),
        migrations.AlterField(
            model_name='display',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='Display_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosenum', models.IntegerField()),
                ('puplish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('displays', models.ManyToManyField(to='display.Display')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
