# Generated by Django 3.1 on 2024-04-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20240407_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='display_data',
            old_name='user',
            new_name='users',
        ),
    ]
