# Generated by Django 3.1 on 2024-04-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20240430_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_data',
            name='displays',
        ),
        migrations.AddField(
            model_name='display_data',
            name='displays',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.display'),
        ),
    ]
