# Generated by Django 3.1 on 2024-05-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('display', '0003_auto_20240430_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_data',
            name='users',
        ),
        migrations.AddField(
            model_name='display_data',
            name='users',
            field=models.ManyToManyField(default=1, to='accounts.UserProfile'),
        ),
    ]
