# Generated by Django 3.1 on 2024-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20240507_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='isyoutube',
            field=models.BooleanField(default=True),
        ),
    ]
