# Generated by Django 3.1 on 2024-04-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240419_1820'),
        ('display', '0005_auto_20240419_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display_data',
            name='users',
        ),
        migrations.AddField(
            model_name='display_data',
            name='users',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
