# Generated by Django 3.1 on 2024-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_display_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='displaydegree',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Display_Degree',
        ),
    ]
