# Generated by Django 3.1 on 2024-04-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240419_1820'),
        ('display', '0006_auto_20240420_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_data',
            name='users',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
