# Generated by Django 3.1 on 2024-06-09 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_auto_20240605_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='word', max_length=150, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='display',
            name='searchtxt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.searchtxt'),
        ),
    ]
