# Generated by Django 3.1 on 2024-06-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_auto_20240609_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='display_data',
            options={'ordering': ['-puplish_date']},
        ),
    ]
