# Generated by Django 3.1 on 2024-06-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_auto_20240617_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='searchtxt',
        ),
        migrations.CreateModel(
            name='searchtxt_display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.display')),
                ('searchtxt', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.searchtxt')),
            ],
        ),
    ]
